# Source: "Think Artificial Intelligence" by Jerry Cuomo, 2024
# Purpose: Educational code examples from the book.
# Copyright © 2024 Jerry Cuomo. All rights reserved.
#
# This code was autogenerated by GPT-4, from the following prompt:
# Prompt: Create a scatter plot for CO2 emissions over time for a random selection of 10 countries using 'annual-co2-emissions-per-country.csv'.
#
# About: This script visualizes CO₂ emissions over time for a random selection of 10 countries. 
# It uses Python's numpy, matplotlib, seaborn, and pandas libraries for data manipulation and visualization.
#
# Setup: Python installed, with 'annual-co2-emissions-per-country.csv' in your directory. 
# Install numpy, matplotlib, seaborn, and pandas using 'pip install numpy matplotlib seaborn pandas'.

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd  # Importing pandas

# Loading the data from the CSV file
co2_data = pd.read_csv('datasets/annual-co2-emissions-per-country.csv')

# Randomly selecting 10 unique countries/areas from the dataset
np.random.seed(0)  # For reproducibility
random_countries = np.random.choice(co2_data['Entity'].unique(), 10, replace=False)

# Filtering the dataset for these countries
filtered_data = co2_data[co2_data['Entity'].isin(random_countries)]

# Creating a scatter plot for these countries
# Create the plot
plt.figure(figsize=(12, 8))
sns.scatterplot(x='Year', y='Annual CO₂ emissions', hue='Entity', data=filtered_data, palette="viridis")

plt.title('CO₂ Emissions Over Time for Selected Countries')
plt.xlabel('Year')
plt.ylabel('Annual CO₂ Emissions (Tonnes)')
plt.legend(title='Country', loc='upper left', fontsize='medium')  # Legend in the upper right
plt.yscale('log')
plt.grid(True)
plt.show()