# Source: "Think Artificial Intelligence" by Jerry Cuomo, 2024
# Purpose: Educational code examples from the book.
# Copyright © 2024 Jerry Cuomo. All rights reserved.
#
# This code was autogenerated by GPT-4, from the following prompt:
# Prompt: Count occurrences of 'percent' and 'carbon dioxide' in the 'text' column of the 'climatebert-netzero-reduction-data.csv'.
#
# About: This script counts occurrences of specific terms ('percent' and 'carbon dioxide') in a dataset and displays the results. 
# It uses Python's pandas library for data manipulation.
#
# Setup: Python installed, with 'climatebert-netzero-reduction-data.csv' in your directory. 
# Install pandas using 'pip install pandas' for data processing.

import pandas as pd
import re

# Load the dataset
data = pd.read_csv('../datasets/climatebert-netzero-reduction-data.csv')

# Count occurrences of 'percent' and 'carbon dioxide' in 'text' column
count_percent = data['text'].str.contains('percent').sum()
count_carbon_dioxide = data['text'].str.contains('carbon dioxide').sum()

# Display the results
print(f"Occurrences of 'percent': {count_percent}")
print(f"Occurrences of 'carbon dioxide': {count_carbon_dioxide}")