# Source: "Think Artificial Intelligence" by Jerry Cuomo, 2024
# Purpose: Educational code examples from the book.
# Copyright © 2024 Jerry Cuomo. All rights reserved.
#
# This code was autogenerated by GPT-4, from the following prompt:
# Prompt: : A personified visualization of 'Dato', a data pile, using scatter plots and bar charts to
# depict characteristics like 'Disorganized yet Insecure', 'Overwhelming yet Resourceful', 'Unpredictably Honest',
# 'Hoarder with Hidden Depths', and 'In Need of Guidance and Clarity'. 
# Each plot should uniquely represent these traits through creative use of colors, highlights, and data points.
#
# About: This script creates a series of subplots to visualize various hypothetical data characteristics, 
# using Python's matplotlib and numpy libraries for plotting and data generation.
#
# Setup: Python installed with numpy and matplotlib. Install using 'pip install numpy matplotlib'.

import matplotlib.pyplot as plt
import numpy as np

# Set up a figure with multiple subplots
fig, axs = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Visualization of Refined Datos Characteristics', fontsize=16)

# Disorganized yet Insecure
x, y = np.random.rand(2, 50)
highlight = np.random.choice([True, False], 50)
axs[0, 0].scatter(x[~highlight], y[~highlight], alpha=0.5)
axs[0, 0].scatter(x[highlight], y[highlight], color='red')
axs[0, 0].set_title('Disorganized yet Insecure')

# Overwhelming yet Resourceful
x = np.arange(100)
y = np.random.rand(100)
axs[0, 1].bar(x, y)
axs[0, 1].bar(x[40:60], y[40:60], color='green')
axs[0, 1].set_title('Overwhelming yet Resourceful')

# Unpredictably Honest
x = np.arange(10)
y = np.random.rand(10) * 10
axs[1, 0].plot(x, y, label='Random Data')
axs[1, 0].plot(x, x*0.5 + 5, label='Underlying Truth', color='orange')
axs[1, 0].legend()
axs[1, 0].set_title('Unpredictably Honest')

# Hoarder with Hidden Depths
x = np.arange(10)
y = np.cumsum(np.random.rand(10) * 10)
axs[1, 1].plot(x, y)
axs[1, 1].scatter([2, 5, 7], [y[2], y[5], y[7]], color='purple')
axs[1, 1].set_title('Hoarder with Hidden Depths')

# In Need of Guidance and Clarity
x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x) + np.random.rand(100) - 0.5
axs[1, 2].scatter(x, y, alpha=0.3)
axs[1, 2].plot(x, np.sin(x), color='red')
axs[1, 2].set_title('In Need of Guidance and Clarity')

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.9)

# Display the plots
plt.show()
